/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.*;
import java.util.*;
import java.awt.image.BufferedImage;



public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
      
        
        String workingDir = System.getProperty("user.dir") + "/working";
        String imageName = "image0";
        String imageDir = workingDir + "/" + imageName;
        Utils.createDirectory(workingDir);
        Utils.createDirectory(imageDir);
        try {
            Image originalImage = new Image(Utils.getImage("http://i.imgur.com/kxXhIH1.jpg"),imageName,"jpg");
            ArrayList<Image> slices = new ArrayList<Image>();
            for(BufferedImage img:Utils.SplitImage(originalImage.image,8,8))
            {
              slices.add(new Image(img,"image" + slices.size(),"jpg"));
            }
           
            for(Image img: slices)
            {
              Utils.WriteImage(img.image,
                img.extension,
                imageDir +"/"+img.name+"-"+ slices.size() +"." +img.extension);
              Utils.WriteHistogram(img,img.extension,imageDir +"/"+img.name+"hist"+"-"+ slices.size() +"." +img.extension);

            }
              //Utils.WriteHistogram()
              //this.WriteHistogram(ims[i],this.extension,this.imageDir +"/"+this.imageName+"-"+"hist"+"-"+ i +"." +this.extension);
          }
          catch(IOException exception)
          {
            System.out.println(exception);
          }
            // catch (IOException e) {
            //         System.err.println(e);
            //     }
            //       for(BufferedImage img: slices)
            //       {
            //         histograms.add()
            //       }
            //       Histogram hist = new Histogram(); 
            //       hist.runHistogram(workingDir);
                  // Buffered Image 
                  // Array Split Buffered Image 
                  // Histogram 
                  
          
    }
}


